package com.thy.loyaltyServicesRest.model.definition;
// Generated Mar 22, 2019 9:45:18 AM by Hibernate Tools 5.1.7.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.thy.loyaltyServicesRest.model.base.AbstractModel;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 * WebserviceMethodConsumer generated by hbm2java
 */
@Data
@Entity
@Table(name = "WEBSERVICE_METHOD_CONSUMER", schema = "LOYALTYDB")
@ToString(callSuper=true,of= {"id"})
@EqualsAndHashCode(callSuper=true,of= {"id"}) 
public class WebserviceMethodConsumer extends AbstractModel implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	private BigDecimal id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WEBSERVICE_METHOD_ID", nullable = false)
	private WebserviceMethod webserviceMethod;
	
	@Column(name = "CODE", nullable = false, length = 64)
	private String code;
	
	@Column(name = "USERNAME", nullable = false, length = 64)
	private String username;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", nullable = false, length = 7)
	private Date startDate;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", nullable = false, length = 7)
	private Date endDate;
}
