package com.thy.loyaltyServicesRest.model.definition;
// Generated Mar 22, 2019 9:45:18 AM by Hibernate Tools 5.1.7.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.google.common.collect.Lists;
import com.thy.loyaltyServicesRest.model.base.AbstractModel;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 * WebserviceMethod generated by hbm2java
 */
@Data
@Entity
@Table(name = "WEBSERVICE_METHOD", schema = "LOYALTYDB", uniqueConstraints = @UniqueConstraint(columnNames = {
		"WEBSERVICE_ID", "NAME" }))
@ToString(callSuper=true,of= {"id"})
@EqualsAndHashCode(callSuper=true,of= {"id"}) 
public class WebserviceMethod extends AbstractModel implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	private BigDecimal id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WEBSERVICE_ID", nullable = false)
	private Webservice webservice;
	
	@Column(name = "NAME", nullable = false, length = 128)
	private String name;
	
	@Column(name = "DESCRIPTION", length = 128)
	private String description;
	
	@Column(name = "STATUS", nullable = false, length = 2)
	private String status;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "webserviceMethod")
	private List<WebserviceMethodConsumer> webserviceMethodConsumers = Lists.newArrayList(); //new HashSet<WebserviceMethodConsumer>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "webserviceMethod")
	private List<WebserviceResultMessage> webserviceResultMessages = Lists.newArrayList(); //new HashSet<WebserviceResultMessage>(0);

}
