package com.thy.loyaltyServicesRest.model.definition;
// Generated Mar 22, 2019 9:45:18 AM by Hibernate Tools 5.1.7.Final

import java.math.BigDecimal;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.envers.Audited;

import com.google.common.collect.Lists;
import com.thy.loyaltyServicesRest.model.base.AbstractModel;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 * Webservice generated by hbm2java
 */
@Data
@Entity
@Table(name = "WEBSERVICE", schema = "LOYALTYDB", uniqueConstraints = @UniqueConstraint(columnNames = "NAME"))
@ToString(callSuper=true,of= {"id"})
@EqualsAndHashCode(callSuper=true,of= {"id"}) //steak overflow hatalar�n� engelliyormu�
@Audited
public class Webservice extends AbstractModel implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	private BigDecimal id;
	
	@Column(name = "NAME", unique = true, nullable = false, length = 128)
	private String name;
	
	@Column(name = "DESCRIPTION", length = 128)
	private String description;
	
	@Column(name = "STATUS", nullable = false, length = 2)
	private String status;
	
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "webservice")
	@OneToMany(mappedBy = "webservice")
	private List<WebserviceMethod> webserviceMethods = Lists.newArrayList();// new HashSet<WebserviceMethod>(0);


}
