package com.thy.loyaltyServicesRest.model.definition;
// Generated Mar 22, 2019 9:45:18 AM by Hibernate Tools 5.1.7.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.thy.loyaltyServicesRest.model.base.AbstractModel;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 * WebserviceResultMessage generated by hbm2java
 */
@Data
@Entity
@Table(name = "WEBSERVICE_RESULT_MESSAGE", schema = "LOYALTYDB")
@ToString(callSuper=true,of= {"id"})
@EqualsAndHashCode(callSuper=true,of= {"id"}) 
public class WebserviceResultMessage extends AbstractModel implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	private BigDecimal id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WEBSERVICE_METHOD_ID")
	private WebserviceMethod webserviceMethod;
	
	@Column(name = "MESSAGE_CODE", length = 64)
	private String messageCode;
	
	@Column(name = "LANGUAGE", length = 2)
	private String language;
	
	@Column(name = "MESSAGE", length = 1024)
	private String message;
	
	@Column(name = "TYPE", length = 16)
	private String type;

}
